Wip feature 9 UI
tako-eng-org/dog_foster_parent_app pull request #23
Opened 2021-03-29 07:33 UTC by tako-eng

## チケットへのリンク
#9 

## やったこと
トップ画面の
- 一覧表示
- ページネーション

## やらないこと
上記以外のこと

## できるようになること（ユーザ目線）
- トップ画面にアクセスし、投稿の一覧を見ることができる
- ページ遷移することができる

## できなくなること（ユーザ目線）
なし

## 動作確認
docker上で一覧表示、ページ遷移できることを確認

2021-03-30 13:07 UTC, MasanoriIwakura requested changes
コメントしました！
ちょっと疲れちゃったのでginのdb周りは次確認します。
なので、他の指摘と同じようなことで直せそうなら修正お願いします。

2021-03-30 13:07 UTC, MasanoriIwakura commented on docker-compose.yml
> +    cap_add:
このへん初めてみた！
何用？

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/.realize.yaml
> +#          output: true
ここは使いたいけど上手く動かない感じ？
今後使うなら良いけど、使わないなら削除しよう！

使いたい場合は `TODO` とかのコメント残しておくと良いね。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/commonController.go
> +	//entity "fpdapp/models/entity"
この辺りもなんでコメントアウトしているか分からないので現在未対応で後から対応するならTODOにしよう！

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +package controller
golangのファイル名ってキャメルケース？
調べた感じスネークケースな気がするんだけど
https://zenn.dev/keitakn/articles/go-naming-rules#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D

golangのリポジトリもスネークケース
https://github.com/golang/go/tree/master/src/bufio

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +//*******************************************************************
あくまで参考なのでこのままで良いけど、GoDocに沿ったコメントにするとこんなこともできる
https://hodalog.com/show-details-of-go-package-using-godoc/

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +func FetchPublishedPostNum(c *gin.Context) {
シンプルに `Count` とかでも良いね！
`PostController` の `Count` だから投稿のカウントだって分かるので

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +	c.JSON(200, result) // URLへのアクセスに対してJSONを返す
`result` は代入しても1箇所でしか使わないから
```go
c.JSON(200, db.CountPublishedPostNum())
```
でも良いかと。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +func FetchIndexRecords(c *gin.Context) {
ここも `Index` だけでも大丈夫！
ginの規則があるのならそれに乗っ取って欲しいところだけど、調べて欲しい。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +	c.JSON(200, result) // URLへのアクセスに対してJSONを返す
ここも同じく `result` に代入しなくても良いね！
`page` まで1行にしちゃうと可読性落ちそうだから `page` はそのままで良いかと。
この辺りもリーダブルコードに書いていた気がする

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +func AddRecord(c *gin.Context) {
シンプルに `Create` にしましょう！

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/postController.go
> +	reqPostImageId := c.PostForm("post_image_id")
この辺りって変数に代入する必要ある？
こんな感じで書いた方がシンプルになるかと。

```go
var record = entity.Post{
    Publishing: c.PostForm("publishing"),
    DogName: c.PostForm("dog_name"),
```

ここから下の数値変換も同時にしてしまえば良いね！

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/docker-entrypoint.sh
> +# realize.ymlにそってホットリロードを実行する
この辺りのメモは全部READMEとかに書くようにしようか！
ソースに書きたい気持ちも分かるけど、説明書が色々なところに散らばっていたら嫌だよね？という気持ちで考えて欲しい。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +            <a class="page-link" href="#" v-on:click.prevent="setPage(1);"><<</a>
`<<` が変になっているけど大丈夫？
16行目も同じく。他にもあるので確認お願いします。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +          <li class="page-item" :class="{'disabled': currentPageEdited == 1}">
`currentPageEdited == 1` の部分、 `currentPageEdited` をboolean(true, false)にできないかな？
そしたらシンプルに `{'disabled': currentPageEdited }` だけで良くなるかと。
他の箇所も同様。

`1` をtrueとして扱うかどうかは人によって認識が異なる場合があったりもするし、俗に言うハードコーディング(マジックナンバー)なので極力避けてください。
https://wa3.i-3-i.info/word12868.html

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +      let vm = this;
ここは変数代入必要？

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +      currentPageEdited: Number, //現在のページ
コメントと変数の意味がちょっとズレている気がする・・・

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +    numFix() {
`Fix` の命名に違和感が。
ページ番号の計算だから `generatePageNum` とかどうだろう？

あと、ページングは自分で計算するとミスること多いからライブラリ使うのも手
https://www.suzunatsu.com/post/vuejs-paginate-to-nuxtjs/

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +      let vm = this;
ここも代入必要？
thisが問題だったりする？

`let vm = this` の部分はあと指摘しないので必要なら修正お願いします。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/pagenation.vue
> +      }
これくらいなら三項演算子の方がスッキリするかも！
```js
return this.totalPages < vm.showPages ? this.totalPages : this.showPages;
```

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +          if ((response.status = 200)) {
ここ、elseの時に先に返しちゃおう！
同じくリーダブルコード読めば書いているはず。

```js
if (response.status != 200) {
  throw new Error('レスポンスエラー');
}
```

あと、 `async` `await` の書き方を使うと `Promise` とか `then` とか消せてスッキリかけるかと。
ちょっと調べてみて使いこなせそうなら直してみてください。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +            }
ここ、フロントで整形しないでginの方で整形してから渡したら？
元の形で使いたいこと無いと思うし。
フロントで整形するとパフォーマンスも良く無いので。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +          if ((response.status = 200)) {
ここも同じく。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +  width: 100%;
`container` ってBootstrapのやつだよね？
ここ上書きすると混乱の元になりそうだから避けようか。

2021-03-30 13:07 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +}
これ知らなかった！
CSSでできるのか。

2021-04-01 23:36 UTC, tako-eng commented on docker-compose.yml
> +    cap_add:
IDE(Goland)でDockerコンテナに接続してリモートデバッグするための設定だよ！
動作確認済です😸

参考URL：（公式ブログ）Docker コンテナー内のプロセスにアタッチする
[https://pleiades.io/help/go/attach-to-running-go-processes-with-debugger.html#attach-to-a-process-in-the-docker-container](url)

2021-04-01 23:39 UTC, tako-eng commented on fosterParentDog/.realize.yaml
> +#          output: true
試行錯誤してる時のゴミが残ってしまってた💦
こういうのちゃんと消さないと、後から混乱するよね。
動作は他の設定でするようになってるから、ここは不要。
TODOナシで、削除しました😸

2021-04-01 23:50 UTC, tako-eng commented on fosterParentDog/controllers/controller/commonController.go
> +	//entity "fpdapp/models/entity"
試行錯誤中の自動補完のゴミが残ってた、削除しました。
今後、コメントのゴミはチェックして残さない＆golangはimportもソートの決めがあるらしく、それに従うことにします。🙇‍♀️

2021-04-02 00:08 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +package controller
ほんとだ。ググってみたら、スネークケースが多かった。
変数名はキャメルケース（スコープに影響する）で、ファイル名とパッケージ名はスネークケースが傾向みたいね。
スネークケースに修正した＆命名を見直ししました。thx!

2021-04-02 00:23 UTC, tako-eng commented on fosterParentDog/controllers/controller/commonController.go
> +	//entity "fpdapp/models/entity"
備忘/保存時に自動でフォーマットかかるように設定した。コメントアウトしたものは反映されないので、ここは手動チェック（もう出ないとは思うけど
![image](https://user-images.githubusercontent.com/45517531/113366664-d4d36a00-9394-11eb-979f-47a6035feba1.png)

2021-04-02 00:26 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +//*******************************************************************
参考URLありがとう！JavaDocみたいな感じで使えるのがgoにもあるんだね。参考にします😸

2021-04-02 00:35 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +func FetchPublishedPostNum(c *gin.Context) {
ここは私のコメントが間違っていて、(下記)でした。ゴメンネ
×全投稿の数を取得する
○"公開済み"フラグの投稿数を取得する

シンプルにしようね、の趣旨は理解できたので、それに合うような命名を考えます😸thx

ちょっと話がそれるけど、現在の命名について冗長だったりわかりにくいところがいくつかあって💦
そもそもpackageの切り分けからよくないやり方をしている気がしてきて、このタイミングで1度、構成を見直したいと思っているところ。
packageの切り分けを変えると、それに引っ張られてある程度ファイルやメソッドの命名も変わってくると思うから、
mtgの時に改めて相談させてほしいな。（実務ではどうすることが多い？みたいなところが聞きたくて、文章にするとややこしいので。）

2021-04-02 00:45 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +	c.JSON(200, result) // URLへのアクセスに対してJSONを返す
なるほど。
1箇所でしか使わないようなのは、いちいち変数にいれんでよかやん、っていう感じかな。（前もあったね）
修正しました。

質問！
どれくらいまとめるかとかは、程度問題というかある程度好みもあるところだと思っていて。
「世界の正解が知りたい！」というわけでなくて、「いわまささん的にどう思うか？」を聞きたいんだけど、
例えば下記の場合

Aパターン
```go
func FetchPostOneRecord(c *gin.Context) {
	postId := c.Query("postId")
	c.JSON(200, db.FindPostOneRecord(postId)) 
}
```
変数`postId`も1箇所しか使ってないから、まとめられるっちゃまとめられる事実。
で、↓ここまでやっちゃうと、私はわかりにくいなと思うんだけど、どう思う？
Bパターン
```go
func FetchPostOneRecord(c *gin.Context) {
	c.JSON(200, db.FindPostOneRecord(c.Query("postId"))) 
}
```

いわまささんだったら、AとBどっちが読みやすいな、と感じる？
今後の参考にしたいから、教えてくれー！

2021-04-02 01:02 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +func FetchIndexRecords(c *gin.Context) {
あーごめん💦前のmtgの時もそれ言ってたよね。
一度修正して色々いじくってるうちにまた遠のいてしまった。ちゃんと`Index`に直しました。

ginの公式、その他qiitaとか読んでみたんだけど、規則はなかったかな。なるべくシンプルにの趣旨でやってきます。
https://github.com/gin-gonic/gin#html-rendering

2021-04-02 01:04 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +	c.JSON(200, result) // URLへのアクセスに対してJSONを返す
（他コメントで言及してくれてるの読む前にした質問、編集して削除しました🐱💦可読性の話。）

2021-04-02 01:05 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +	c.JSON(200, result) // URLへのアクセスに対してJSONを返す
どこまでやるかの話ね。リーダブルコードを読み直します...👀

2021-04-02 01:06 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +func AddRecord(c *gin.Context) {
修正しました！なるべく簡潔に、シンプルにしようの趣旨。

2021-04-02 01:36 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +	reqPostImageId := c.PostForm("post_image_id")
なるほど。変数に代入する必要のないものは削除しました😸


> ここから下の数値変換も同時にしてしまえば...

これはいい方法が思いつかず、折衷案で修正しました。
数値変換の関数`Atoi`については戻り値が複数あって、
`func Atoi(s string) (int, error)`
1つめがint, 2つめがerror,なのね。（実装ではエラーハンドリングしないので、errorはアンスコ_で捨てている）
でも、2つめの戻り値を受け取らないとコンパイル通らないので、下記のようにしました。

```go
func Create(c *gin.Context) {
	// 数値に変換する
	publishing, _ := strconv.Atoi(c.PostForm("publishing"))
	gender, _ := strconv.Atoi(c.PostForm("gender"))

	// テーブルに登録するためのレコード情報
	var record = entity.Post{
		Publishing:             publishing,
		DogName:                c.PostForm("dog_name"),
		Breed:                  c.PostForm("breed"),
		Gender:                 gender,
```

2021-04-02 01:56 UTC, tako-eng commented on fosterParentDog/docker-entrypoint.sh
> +# realize.ymlにそってホットリロードを実行する
承知...！説明書が散らばっていたら嫌だ。と納得した。
デバッグ用のステートメント除き、メモは全部READMEに入れるよう修正しました😸
READMEについて、階層ごとに作るとどこに入れたかわからなくなるから、ひとまず1つに全部入れて、後から整理することにした。

2021-04-02 02:02 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +            <a class="page-link" href="#" v-on:click.prevent="setPage(1);"><<</a>
確認しました！ページネーションの最新ページに戻る`<<`や、1ページ前に戻る`<`の文字列だから、ここは大丈夫、と思っています😸
![image](https://user-images.githubusercontent.com/45517531/113371956-7ad9a100-93a2-11eb-9816-b26322fd394e.png)

2021-04-02 04:42 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +          <li class="page-item" :class="{'disabled': currentPageEdited == 1}">
この`1`は、1ページ目(最新ページ)の`1`だから、booleanにしないで数字で使おうと思ってる。
ただややこしいから、下記の通り修正しました😸

- 他コメントでも指摘もらってるけど、変数`currentPageEdited`の命名がわかりにくいので、`currentPageNum`に修正した。
- マジックナンバーを使うのはよろしくないので、最新ページを示す変数`newestPageNum`を定義した。

```pagenation.vue
    <div class="col-auto">
      <nav aria-label="Page navigation">
        <ul class="pagination">
          <!--     現在、最新ページにいる場合、最新ページへ移動するリンク << を無効にする     -->
          <li class="page-item"
              :class="{'disabled': currentPageNum == newestPageNum}">

```

2021-04-02 04:44 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +      let vm = this;
不要で冗長だね🤭変数`vm`を全部`this`に置き換えました。（動作確認済）

2021-04-02 04:46 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +      currentPageEdited: Number, //現在のページ
修正しました🐱

> `currentPageNum`に修正しました。

https://github.com/tako-eng-org/dog_foster_parent_app/pull/23#discussion_r606068579

2021-04-02 04:51 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +    numFix() {
確かに...`generatePageNum`に修正しました。
他の指摘でももらったけど、メソッド名はわかりやすいやつつけるように気をつける💦訓練が必要だ。

vueのpaginateは知ってて＆使用を考えたんだけど、
今の私にはライブラリ使うほうが学習コストが高い気がして手組みにしてしまった。
もう少しvue慣れたらライブラリに置き換えるかも。教えてくれてありがとう！

2021-04-02 04:52 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +      let vm = this;
https://github.com/tako-eng-org/dog_foster_parent_app/pull/23#discussion_r606068953
にて合わせて、全て修正しました。

2021-04-02 04:54 UTC, tako-eng commented on fosterParentDog/frontend/components/pagenation.vue
> +      }
三項演算子慣れないよ〜、短いやつなら断然こちらの方がスッキリだね💦使うようにする...
修正しました！

2021-04-02 05:01 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +          if ((response.status = 200)) {
elseで先に返すように修正しました。
前回、正常系はtrueルート、異常系はelseルートでやろうって決めてたからその名残なんだけど、これくらい処理が長くなってきたら、異常系は先に返しちゃった方が良いね。

`async` `await` については実装前に調べてあることは知ってるのだけど、ちょっと使いこなせる自信がなくて日和って`Promise`使ってる...もう少しjs書けるようになったら直すので、今はこのまま進ませてください🐱投稿機能を作り終えたあたりで少し書けるようになってる(はず)だから、見直しします。

2021-04-02 05:02 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +          if ((response.status = 200)) {
https://github.com/tako-eng-org/dog_foster_parent_app/pull/23#discussion_r606072714
にて合わせて修正しました。

2021-04-02 05:29 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +  width: 100%;
そう！Bootstrapのやつ。
topクラスを作成して、それにCSS設定するように修正しました😸フレームワークの要素には、なるべく上書きしないようにする

2021-04-02 05:31 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +}
できるみたい！
ベストプラクティスかどうかはわからないけど、一番手軽に実装できる方法と判断して採用しました😸

2021-04-06 12:42 UTC, tako-eng commented on fosterParentDog/controllers/controller/postController.go
> +	reqPostImageId := c.PostForm("post_image_id")
できる限り修正したものをcommitしました。
当画面の動作確認に使っていて間違えてcommitしてしまったけど、正確には当画面機能ではない（投稿記事作成機能で使用するAPI）のため、ちゃんとした見直しは該当機能の実装時に再度します。

2021-04-06 12:44 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +            }
バックエンド(gin)で整形（YYYY-MM-DD hh:mm）するよう修正しました。
シリアライザーなど役割によって分割することを考えるきっかけにもなった、ありがとう！
クライアントで使わない情報は、なるべくバックエンドで切り分けるように気をつけます。

2021-04-06 12:47 UTC, tako-eng commented
レビューありがとう！
指摘頂いたところについて、修正しました。（一部、当機能以外でもcommitしてしまったものがあり、それらの指摘についてはできる限り修正したけど、ちゃんとした修正は該当機能を実装するときに再びする予定です。）

2021-04-07 01:56 UTC, merged