Feature 18
tako-eng-org/dog_foster_parent_app pull request #24
Opened 2021-04-11 06:19 UTC by tako-eng

## チケットへのリンク
#18 

## やったこと
投稿詳細画面機能の作成
- トップ画面で選択した投稿IDの詳細画面へ遷移し、投稿記事を閲覧することができる。（記事の基礎情報、投稿者のプロフィール）

## やらないこと
- "やりとりする"ボタンの実装。設計時に決めた通り、追加機能として扱うので。
- 見た目を綺麗にすること。cssは最後にまとめて行うため。
 
## できるようになること（ユーザ目線）
(主にトップページから)選択した投稿IDの投稿詳細画面へアクセスし、投稿記事を閲覧できるようになる

## できなくなること（ユーザ目線）
なし

## 動作確認
docker上での動作確認済

```
cd ~/dog_foster_parent_app/fosterParentDog/frontend
yarn generate
--
docker-compose build --no-cache
docker-compose up -d nginx
docker-compose ps
```
`localhost:8080/`へアクセスし、アプリのトップ画面から投稿詳細画面(当画面機能)へ遷移できます。

## その他
なし

## サンプル画面
![image](https://user-images.githubusercontent.com/45517531/114294343-ef19f000-9ad8-11eb-9483-34316610c6c1.png)

2021-04-11 14:26 UTC, MasanoriIwakura requested changes
レビューしました。
同じ指摘はあまりしなかったので、同様の箇所も修正お願いします。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +func (pc *PostController) CountPublishedPostNum(c *gin.Context) {
すごく細かいけど、 命名に `Count` と `Num` が入っているの冗長じゃない？
`CountPublishedPost` でも公開済み投稿のカウントだって分かるかと！

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +func (pc *PostController) FetchPostOneRecord(c *gin.Context) {
ここの命名も冗長なのでもう少しシンプルに！
他の箇所は指摘しないので冗長な箇所は修正お願いします。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +// 投稿idをもとに、投稿画像を取得する
ここのコメント変じゃない？
画像用のfuncじゃない気がする。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/models/entity/transferable_prefecture.go
> +type TransferablePrefecture struct {
投稿に紐づく「譲渡可能都道府県」のテーブルだからこの命名なのは分かるけど、
投稿に紐づく都道府県なので、 `post_prefectures` テーブルが良いかと。
こちらの方が「投稿に紐づく」ってことがシンプルに分かりやすいかと。

テーブル名だけ見たら投稿と紐づいていることが分からなかったので。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/assets/json/prefecture.json
> +[
都道府県はフロントで持たないでAPI側から取得してください。
フロントはそれを呼び出して使うだけ。

基本的にフロントでデータを保持するような構成はNGでお願いします。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/assets/json/gender.json
> +]
ここは少ないからselectタグに直指定で良いかと。
gender用のコンポーネント作ると良いね！

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/assets/json/gender.json
> +]
都道府県以外はgenderと同じ指摘でお願いします。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/nuxt.config.js
> +}
この辺はまたチャレンジだね！

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +<template>
お！ダイナミックルーティング良いね！

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +        <div class="transferable" v-for="record in transferable_prefectures" v-bind:key="record.post_id">
細かいけど、 `record` よりは `prefecture` が適切かと。
他の箇所は指摘しないので自分で考えてみてください。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +      <div class="row"><p>性別 : {{ $getLabel(gender_map, record.gender) }}</p></div>
別の箇所で指摘したけど、ここはコンポーネントを使うと良いね！
`getLabel` は全部同様。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +             height="180">
5行目でも同じようなimgタグがあるから、コンポーネントにしてください。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +const axios = require('axios');
この書き方はES5の書き方なので、 `import` で統一してください。
そもそも `axios` はグローバルで使えるようになっているはずなので定義不要かと。 `$axios` とかで呼べないかな？
https://axios.nuxtjs.org/

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +process.env.DEBUG = 'nuxt:*' // nuxt.jsについてログ出力する
これ何用？？
`nuxt.config.js` で書くなら良いけど、ここで書く内容ではない気がする。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +      records: [], // 投稿記事
postsにしよう！

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +      transferable_prefectures: [], //譲渡可能都道府県
JSはキャメルケースで変数定義お願いします！

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +  },
78~82行目は残骸？
不要なら削除してください。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +    this.doFetchUserProfile(this.$route.params['id']);
API側で指摘するか迷ったんだけど、ここで指摘した方が分かりやすいのでここで指摘します。

APIとの通信は極力するなくしないとパフォーマンスが悪くなるので、今回は1回で終わるようにしましょう。
(例外的に複数回のパターンもあるので間違いではない)

APIでJSONにまとめてレスポンス返すようにすればOK
ex.)
```json
data: {
    "posts": [
        {
            "id": 1,
            "name": "犬の名前",
            "images": [
                { "name": "画像の名称", "url": "https://s3.xxxxxxx" }
            ]
        }
    ],
    "profile": {
        "id": 1
    }
}
```

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +    doFetchOneRecords(currentPostId) {
`One` なのに `Records` は複数形？？
`getDetail` とかで良いかと。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/detail/_id.vue
> +          throw new Error('レスポンスエラー')
このエラーメッセージだと分かりにくいので何のエラー分かるようにしようか。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
>      doSetPagenation() {
すごく細かいけど、do無くても意味同じだから `setPagination` でも大丈夫だね。
ただ、 `set` だとセッターみたいな意味に取られるから `generatePagination` とかが良さそう。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +        axios.get('api/published_post_count').then((response) => {
今更思ったけど、 `published_post_count` のエンドポイントじゃなくて
`post_count` のエンドポイントを作成してクエリで公開、非公開を指定できた方が汎用性高くないかな？

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/frontend/store/todos.js
> +}
`todos.js` ？？？？

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/models/db/db.go
> +	db.db.Table(PostTable).
仕方がないと思うけど、 `db.db` って分かりにくいね・・・

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/models/db/db.go
> +	err := db.db.Where("id = ?", postId).First(&model).Error
ここってシンプルに書けない？
```go
err := db.db.First(&model, postId).Error
```

参考
https://gorm.io/ja_JP/docs/query.html#Retrieving-objects-with-primary-key

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/models/db/db.go
> +			" "+PostImageTable+".image_path").
この辺、文字列結合しんどくなっているのでテーブル名の変数代入やめない？
そんなにテーブル名変わることないし。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/models/db/db.go
> +func (db *Database) FindIndexRecords(page string) ([]entity.Post, error) {
Slackでフォルダ構成の例を示した時に提案したけど、共通処理は`db.go` に残して各テーブルの操作は `post.go` とかに分けない？って提案したのはボツ？

全部 `db.go` で処理するとかなり肥大化すると思う。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/models/entity/post.go
> +}
これ全テーブル、全項目作成するのしんどいね・・・
これはバリデーション用？

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/serializers/post_serializer.go
> +	EntityPost []entity.Post
このクラス初見なんだけど、差分になっているのは一度プルリクせずにマージしたから？

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/serializers/post_serializer.go
> +	var retSlice []PostResponse
serializerは配列で返却ではなく、1つのオブジェクトで返却するようにしてください。
外側でserializerをループで呼んで配列に詰め込むイメージ。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/serializers/post_serializer.go
> +// PostImage
Serializerのファイル分けてください。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/serializers/post_serializer.go
> +// PostTransferablePrefecture
ここも分けてください。

2021-04-11 14:26 UTC, MasanoriIwakura commented on fosterParentDog/serializers/user_serializer.go
> +	for i := 0; i < len(myModel); i++ {
ここもpostの指摘と同じ。

2021-04-11 23:48 UTC, tako-eng commented on fosterParentDog/frontend/assets/json/prefecture.json
> +[
質問です！
フロントでデータを保持しない、のデータが何を指しているか理解しきれなかったから教えてほしい。↓

現状：フロントとバックエンドのデータやりとりは都道府県ID(1や[1, 2, 10])で行っている。
文字列が必要な場合は、それぞれで読み替えを行っている。(ここでいうprefecture.jsonのラベルを取得する関数)

理想：フロントからバックエンドへのデータやりとりはidに紐づいた文字列("埼玉県"等)で行う。idと都道府県名の読み替えはバックエンドで行う。

↑理想の形に寄せるべし、という認識であってる？
そうすると、性別(女の子/男の子)とか、譲渡ステータスとかも現状、フロントでjsonを持っていて読み替えてるんだけど、それも変えたほうが良いのか、教えてください。

2021-04-11 23:56 UTC, tako-eng commented on fosterParentDog/models/db/db.go
> +func (db *Database) FindIndexRecords(page string) ([]entity.Post, error) {
今slack読み返したら読み間違えてたことに気づいた。
「post_db.goを廃止してpost.goに移植」をdb.goに移植、に読み間違えてた。（分けようねという話は覚えている）
失礼、entity.post等に移植します。

2021-04-12 00:02 UTC, tako-eng commented on fosterParentDog/models/entity/post.go
> +}
うん、バリデーション用。
以前、トップ画面のコードレビュー時に「Form送信時のパラメータの書き方が不統一」という指摘をもらって、どうしたら綺麗に書けるかなと考えた末の策なの。
指摘もらって直したのはこの辺りです↓
[https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-ef12b9ccfac9fc92bbf4cf97a04fad2289b64909438d4c456446b2c6627c78a0R42](url)

バリデーション用なら、フィールドごとの関数(SetPublishing等)ではなく型ごとの関数(castInt等)でもいいかな？

2021-04-12 00:08 UTC, tako-eng commented on fosterParentDog/serializers/post_serializer.go
> +	EntityPost []entity.Post
クラスと言っているのはファイルそのものを指しているかな、
serializerの処理は、前回の"トップ画面"のレビュー(4/5)後修正で追加した記憶がある。4/6に後からみるからマージしてOKって言ってたやつ。
プルリクせずにマージしたのはかなり初期だから、ここは違うんじゃないかな？と思います。

2021-04-12 00:14 UTC, tako-eng commented on fosterParentDog/serializers/post_serializer.go
> +// PostImage
承知。
serializerはcontrollerと基本的に対になる、という運びなんだけど(4/5slackにて)、PostImageのcontrollerも作成するのか。
controllerはざっくり機能ごとに分ける（post,userくらいの粒度）という認識でいたので、投稿機能にかかるこのPostImageについてserializerのファイル分けるっていうの、考えはしたんだけどちょっと迷ってそのままにしたんだ。
でもリポジトリが大きくなったら訳わかんなくなりそうだし、分割したほうが良いよね。ありがとう！

2021-04-12 00:16 UTC, tako-eng commented on fosterParentDog/frontend/assets/json/gender.json
> +]
少ない場合 -> フロントでコンポーネント化
多い場合 -> バックエンドで処理
という感じかな。少ない多いの基準の勘所がわかってないけど、なんとなくイメージできたかも。

コンポーネント化について試してみます、ありがとう。

2021-04-12 01:46 UTC, MasanoriIwakura commented on fosterParentDog/serializers/post_serializer.go
> +	EntityPost []entity.Post
serializerの導入提案してからプルリクもらったの初めてじゃないかな？勘違い？
4/5にserializerを提案して、そこから4/11時点でプルリクもらっていないから初見な気がする。

見つけた。ここでレビュー後に再レビューせずに入れてるね。
https://github.com/tako-eng-org/dog_foster_parent_app/pull/23
https://github.com/tako-eng-org/dog_foster_parent_app/commit/5c937922349b2ee4c1b6d40281751b8b879a4879

レビューせずにマージするんだったらレビューの意味なくなるので、最初のうちは量が多くて大変だけどちゃんと見るので再レビューもください！

2021-04-12 01:57 UTC, MasanoriIwakura commented on fosterParentDog/frontend/assets/json/gender.json
> +]
ごめん、多い少ないのコメントしちゃったけど
どこでデータを管理すべきか？で分けて欲しい。

都道府県については今回API側でテーブル持っているので、これだと二重管理だよね？
例えば、北海道を一時的に非公開にしたい時にAPI側だけで管理していたらAPIのレスポンスに含めないようにすれば
フロント側の修正は不要になる。

性別とか他の項目についてはAPI側で別テーブルに分けたりしていないし、逆にフロントで入力した内容をDBに保持するからフロント側で0,1,2とかの値で選択する方式でOK。
2を入力禁止にしたいときはフロントの項目から2を消すだけでOKだからね。

2021-04-12 10:38 UTC, tako-eng commented on fosterParentDog/serializers/post_serializer.go
> +	EntityPost []entity.Post
そういうことか、
前に間違えた時以降は、原則「マージしてOK」の許可(?)貰うまではマージしない運用にしてるつもり。だから今後、レビュー後修正でクラス追加や大きい修正を入れた時は、その旨伝えて再レビューお願いって言うようにします！

大変なのにちゃんと見てくれてありがとう！助かる。

2021-04-12 11:00 UTC, tako-eng commented on fosterParentDog/frontend/assets/json/gender.json
> +]
二重管理、確かに！
API側では文字列（"北海道"や"東京"）を使う機会がなくて、フロントとのやりとりは全てid(1や[1,2,10])で行ってるんだよね。DBでは情報を`譲渡可能都道府県テーブル`で投稿管理idと都道府県idで管理していて、API側で文字列は一切登場しない。

指摘されて気づいたけど、そもそも現状、**都道府県マスターテーブルってどこでも使ってないし使う予定もない。**

いわまささんのコメントの**どこでデータを管理すべきか？**を考えて、
性別とか他の項目と同じ扱いに変更しようかなあ、と思いついた。
・API側で、都道府県マスターテーブルを持たない（削除する）
・API側では、譲渡可能都道府県テーブルにidを保持するのみにして、文字列はフロントで読み込むようにする。（性別とかと同じ）
↑これで困ることないか？等、もう少し考えて修正入れます。

どこでデータ管理すべきか？って、今までちゃんと考えてなかったかも。
勉強になります＆コメントありがとう！

2021-04-14 08:08 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +func (pc *PostController) CountPublishedPostNum(c *gin.Context) {
指摘の箇所を`CountPublishedPost`に修正して、それ以外の関数名（front, API両方）についても全て見直し修正しました。
リーダブルコード読み直してこれぞという関数名に修正したので、もう大丈夫...なはず。
また気になる命名してたら声かけてもらえると助かる！

2021-04-14 08:10 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +func (pc *PostController) FetchPostOneRecord(c *gin.Context) {
`FetchOnePost`に修正した！
命名修正の水平展開については、上記コメントに同じく修正済です。

2021-04-14 08:13 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +// 投稿idをもとに、投稿画像を取得する
ごめん、コピペして直すの見落としてた。
この関数（現在は`FetchPostPrefecture`に命名修正済）については、下記が正しく修正済です。
// 投稿idをもとに、譲渡可能都道府県idを取得する

2021-04-14 08:17 UTC, tako-eng commented on fosterParentDog/models/entity/transferable_prefecture.go
> +type TransferablePrefecture struct {
確かに、命名から判断つかないね。

「譲渡可能都道府県」を扱うような箇所の命名を全て
transferblePrefecture -> postPrefecture に修正しました。

指摘もらったこの箇所についてだけ言えば、「譲渡可能都道府県テーブル」自体が不要になったので、削除した。（下記コメント）
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r611530371

2021-04-14 08:21 UTC, tako-eng commented on fosterParentDog/frontend/assets/json/prefecture.json
> +[
都道府県テーブルをAPI側で使うことがなくて、テーブル自体が不要になったので、削除しました。

API側ではpostPrefecture(譲渡可能都道府県テーブル)で、都道府県idを持つだけ。
文字列などのマスタデータをフロントで保持する、というやり方にした。（下記コメント）
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r611530371

2021-04-14 08:22 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +<template>
うれしい！ありがとう。

2021-04-14 08:27 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +        <div class="transferable" v-for="record in transferable_prefectures" v-bind:key="record.post_id">
ドキュメントを読むと`v-for="post in posts"`みたいに`単数系 in 複数形`と記述しているところが多く公式もそうだったから、倣って修正しました！（前述の通り、水平展開済み）
`p in post`みたいにしているところもあって、見やすくて気に入ったんだけど...公式原理主義ということで。

2021-04-14 08:34 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +             height="180">
`Image.vue`というコンポーネントを作成して、同じimgタグ使っているところを切り出した。

確かにそうね。
今後、同じようなのはどんどんコンポーネントに切り出していくようにします。

file changeの`Image.vue`
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-9b3739ba7408716e3dffcc75d0ba927b978119e031579792c1e220efcc349659

2021-04-14 08:45 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +const axios = require('axios');
指摘ありがとう、ES5とES6の意識全然してなかった...これから気をつけます。
修正後
```
import axios from 'axios';
```

> $axios とかで呼べないかな？

できなかった。。URL先の公式の通り、yarn add して modulesに含めた状態で呼んでみたら
`Uncaught (in promise) ReferenceError: $axios is not defined`
多分primise使ってるのが関係してるっぽく、調査中。
しばらくやってダメなら諦めてimport使います。公式に書いてあるってことは使えるはずだからゆくゆくは直したい。

2021-04-14 08:55 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +process.env.DEBUG = 'nuxt:*' // nuxt.jsについてログ出力する
ステートメント削除しました。

[nuxtの公式](https://ja.nuxtjs.org/docs/2.x/internals-glossary/nuxt/#%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E3%83%AD%E3%82%B0) にデバッグログ出せる的なこと書いてあって初期に入れたんだけど、確かにここに書くことじゃないね。
`nuxt.config.js`の先頭にも書いてみたんだけどどこにもログが出ないので、結局削除しました。

蛇足：
[公式issue](https://github.com/nuxt/nuxt.js/issues/2047#issuecomment-371847584) には`nuxt.config.js`の`debug:true`にしてファイルにログだせって言ってる。前回、これも効かなかったような。

2021-04-14 09:03 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +      records: [], // 投稿記事
指摘通り`posts`に修正しました。
トップ画面作ったときは取得する配列が1つだったから`records`でなんとも思ってなかったけど、データが増えた今recordじゃ訳わかんないよな。と気づいた。ありがと

change fileのURL貼ることを覚えたので、やってみます↓
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-02a1828de961e3d5dcb28da7bf50e1d8a1cf8d38ed3a9a6a760f4d3dc55c19aeR56

2021-04-14 09:05 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +      transferable_prefectures: [], //譲渡可能都道府県
キャメルケースに修正しました。（水平展開済み）
定数のときはIMAGE_PATHSみたいにする。
命名についてご迷惑をおかけしております...今後命名については指摘受けないように気をつけるわ。

2021-04-14 09:11 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +  },
関数削除しました。
既存処理でcomputedを使うべきっぽいところがあるけど実装できてなくて(今も)、なんとなく残してしまってた。

2021-04-14 09:12 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +    doFetchOneRecords(currentPostId) {
`getDetail`に修正しました。（命名について水平展開済み）
oneなのに複数形なのおかしいね。気をつけます

2021-04-14 09:15 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
>      doSetPagenation() {
`generatePagination`に修正しました。
doはなくても伝わるから意味ないって、リーダブルコードにも書いてあった
（命名修正については水平展開済み）

[変更後](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-02a1828de961e3d5dcb28da7bf50e1d8a1cf8d38ed3a9a6a760f4d3dc55c19aeR102)

2021-04-14 09:25 UTC, tako-eng commented on fosterParentDog/frontend/store/todos.js
> +}
ごめん、サンプルファイル間違えてpushしてチェックの時見落としてた...
削除しました。

2021-04-14 09:32 UTC, tako-eng commented on fosterParentDog/models/db/db.go
> +	db.db.Table(PostTable).
同感。`db.connection.Table("posts").`のように修正しました。 [修正後](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-ae74401442765adb2bf20645afd4618cb8ac1c8fa7a444207b41706cfbadb11bR14)
自分で読んでこちらの方がわかりやすいと感じたけど、この命名が良いか自信ない。後でまた直すかも

2021-04-14 09:36 UTC, tako-eng commented on fosterParentDog/models/db/db.go
> +	err := db.db.Where("id = ?", postId).First(&model).Error
本当だ！公式まで貼ってくれてありがとう助かるよ。
修正しました。 [修正後](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-ae74401442765adb2bf20645afd4618cb8ac1c8fa7a444207b41706cfbadb11bR112)

他のCRUD文もおいおい見直します...

2021-04-14 09:38 UTC, tako-eng commented on fosterParentDog/models/db/db.go
> +			" "+PostImageTable+".image_path").
テーブル名の変数代入やめました。
その通り、ちょっとしんどくなってた。

今は試行錯誤中だからテーブル名コロコロ変わってるけど、
ちょっと安定しはじめたら、確かにそんな変わることないものね。

2021-04-14 09:41 UTC, tako-eng commented on fosterParentDog/serializers/post_serializer.go
> +// PostImage
（未解決）
分割しました。 [post_image_serializer.go](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-541fb5af6a7651df9ed77e80976bc04bb956942d69cb9124f6e64cdb44289e11R1)のように

実装で、分割したはいいけどどうしたらいいか悩んでるところがあって、次回mtgで色々相談したい。（とりあえず分割するだけした、というメモです）

2021-04-14 09:43 UTC, tako-eng commented on fosterParentDog/serializers/post_serializer.go
> +// PostTransferablePrefecture
分割しました。[post_prefecture_serializer.go](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-4c61834b9fe034d87e79d4c94aae633f48a7cc0433692175941ec706eab8671dL1)

ノリは https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r613098146 と同じ

2021-04-15 06:27 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +          throw new Error('レスポンスエラー')
（未解決）
別問題があったので自分用に記録します。

例えば409エラー（ステータスコードは適当）を返すようにしてみたところ、ブラウザコンソールに下記を表示した。つまり、エラーは発生する。
```
Failed to load resource: the server responded with a status of 409 (Conflict)
Uncaught (in promise) Error: Request failed with status code 409
（訳：リソースの読み込みに失敗しました：サーバーから409（Conflict）のステータスで応答がありました。
Uncaught (in promise) Error: リクエストはステータスコード409で失敗しました。）
```
しかし、ifルート内で`console.log("エラー")`としてもブラウザコンソールにlog出力しなかった。

`.catch(err => alert(err));`を追記することで気づけるようにはしたが、期待動作とは異なるので要修正。

2021-04-15 07:04 UTC, tako-eng commented on fosterParentDog/models/db/db.go
> +func (db *Database) FindIndexRecords(page string) ([]entity.Post, error) {
mtg時に口頭で説明＆相談するつもりなので、以下は読まなくて大丈夫です。

共通処理は`db.go(dbパッケージ)`に残して各テーブルの操作は`post.go(entityパッケージ)`に分ける話、下記のように構成見直すかも。

dbパッケージ -> DB操作にかかる処理を定義する（`post_db.go`や`user_db.go`を作成する）
entityパッケージ -> DBテーブル用の構造体を定義するだけ

理由としては、dbパッケージ側でOpen()などのDB接続を定義すると、その接続の状態をentityパッケージ側と共有できないから。レシーバ(Database接続用のstruct)によって接続状態を共有するが、レシーバに使用する型は同じパッケージ内で宣言するというルールがある。

serializerの例も参考にしてみたら、私のPJでいうdb(DB操作にかかる処理)とentity(テーブル定義)を分けずに同じパッケージにしているから、そもそもパッケージを分けなくていいんじゃない？みたいな話は出てくるかもだけど...
私は分けた方が良いと思っているので、ひとまずこの切り分けで処理書いてみます。

2021-04-15 07:08 UTC, tako-eng commented on fosterParentDog/frontend/assets/json/gender.json
> +]
API側では文字列（"埼玉県"とか）を使う機会がないので、都道府県マスターテーブルを削除しました。
slackで相談させてもらった通り、jsで共通データ(`{id:1, name:"埼玉県" ...}`みたいな感じで)を保持するよう修正した。

2021-04-15 09:52 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +      <div class="row"><p>性別 : {{ $getLabel(gender_map, record.gender) }}</p></div>
なるほど！
nuxtのグローバル定数はpluginで定義することが多いみたいなので、
`@plugin/map/gender.js`のように各自ファイル作成して、定義しました。

https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-e4dd97c086e8311ec12172dab789df768defa05a19f2ea0b101b7aae97148311R1

2021-04-15 09:58 UTC, tako-eng commented on fosterParentDog/models/entity/post.go
> +}
controllerから使うFormの整形用だから、controllerの共通関数として定義し直しました。

2021-04-15 10:07 UTC, tako-eng commented on fosterParentDog/serializers/post_serializer.go
> +	var retSlice []PostResponse
ここ最初サンプルみてもわからなくてエイヤでやってしまっていたけど、（こんなもん見させてごめんね）
いま見返したら出来そうな気がして修正しました。できた、多分きれいになったはず。

前に教えてもらったserializerサンプルを参考に、下記のような構成にしたよ。
```
PostSerializer（コンテキストとモデルを持つstruct）
PostsSerializer（コンテキストと[]モデルを持つstruct）

PostResponse（jsonとか定義するstruct。これは1個で良い）

(s *PostSerializer) Response() PostResponse
(s *PostsSerializer) Response() []PostsResponse
```

2021-04-15 10:14 UTC, tako-eng commented on fosterParentDog/serializers/user_serializer.go
> +	for i := 0; i < len(myModel); i++ {
修正しました。 [修正後](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-b773da1bcae47897b4bfb8d9b3ca651e75d3d3677fc13c678cd88ee1ab5874d9R1)

↓と同じ感じ
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r613938438

2021-04-16 22:20 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +        axios.get('api/published_post_count').then((response) => {
その発想なかった！確かにそうね。
post_countのエンドポイントを作成して公開/非公開を指定するよう修正しました。 [修正後](https://github.com/tako-eng-org/dog_foster_parent_app/pull/24/files#diff-02a1828de961e3d5dcb28da7bf50e1d8a1cf8d38ed3a9a6a760f4d3dc55c19aeR100)

2021-04-16 22:48 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +// 投稿idをもとに、投稿画像を取得する
APIをまとめたので、この関数は削除しました。（`FetchPost`に統合）

2021-04-16 23:31 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +func (pc *PostController) CountPublishedPostNum(c *gin.Context) {
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r611191794
の修正（公開/非公開を指定する）修正にしたので、`CountPost`になった。

2021-04-17 13:18 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +<template>
(mtg発のお話)ダイナミックルーティングをやめ`/pages/detail/_id.vue`を`/pages/detail`に移動しました。

2021-04-17 13:20 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +    this.doFetchUserProfile(this.$route.params['id']);
1つのAPIにまとめるよう修正しました。`/api/post`

2021-04-17 13:23 UTC, tako-eng commented on fosterParentDog/frontend/pages/detail/_id.vue
> +          throw new Error('レスポンスエラー')
今は開発に困らなければいいかな、くらいのレベルで、ステータスコード＆どのメソッドのルートかくらいを出力するよう修正しました。
nuxt.config.jsのvueコンフィグで、デバッグログを出力するよう修正したので、devtoolでデバッグできるようになった！

2021-04-17 13:28 UTC, tako-eng commented
ここでもコメントしたほうが、区切りがわかりやすいかなと思い投稿、
レビューとmtgありがとう、レビュー後修正したので、再レビューよろしくお願いします！

指摘以外のmtgとかででた修正は、ざっくり以下
・ダイナミックルーティングをやめた（generateで動かない）
・項目をコンポーネント化した
・cssのスコープを入れた

2021-04-19 01:24 UTC, MasanoriIwakura requested changes
レビューしました！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/common_controller.go
> +//*******************************************************************
今はいいけど、命名がとても分かり易いからここのコメント無くても大丈夫だね！
命名が適切だからstringからintにするって分かるし。

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +	publishParam := c.DefaultQuery("publishing", "0") // デフォルト ?publishing=0(公開)
"0"の部分ってenumやら構造体やらで表現できないかな？
前にも指摘したけどハードコーディング(マジックナンバー)は避けて欲しい！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/models/db/post_db.go
> +func (db *Database) FindIndex(page string) []entity.Post {
`公開済み投稿` ってコメントあるけど、クエリにPublishingの条件無くない？
ここも引数で公開・非公開指定できると良いね

あと、page以外の条件を追加したくなる可能性高いので引数はMaps(連想配列)にした方が良いかと！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +	// post
変数名分かりやすいから、 `post` , `postImage` , `postPrefecture` , `postUser` のコメント無くても大丈夫だね！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +	r.User = postUserSerializer.Response()
こんな感じで初期化したらスマートじゃない？
構造体使い回す事ないし！
```go
response := struct {
    Post            serializers.PostResponse             `json:"post"`
    PostImages      []serializers.PostImageResponse      `json:"post_images"`
    PostPrefectures []serializers.PostPrefectureResponse `json:"post_prefectures"`
    User            serializers.UserResponse             `json:"user"`
}{
    postSerializer.Response(),
    postImageSerializer.Response(),
    postPrefectureListSerializer.Response(),
    postUserSerializer.Response()
}
```

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/TheAppealPoint.vue
> +<template>
他のもそうだけど、ファイル名の `The` 必要？？

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/TheGender.vue
> +      <p>性別 : {{ $getLabel($GENDER, gender) }}</p>
`$GENDER` みたいなグローバルスコープNGでお願いします！
`genders.js` を作成して、
```js
import genders from "genders";
```
みたいにimportして欲しい。

グローバルだとどこで定義しているか分かりにくいのと、廃止したときに動かすまで消し忘れに気が付かない。
importの場合だとソースが消されていたらビルドでエラーに気がつくので！

他の箇所は指摘しないので同様にグローバルはNGでお願いします。

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/Image.vue
> +    imagepath: String, //画像URL
細かいけど `imagePath` で！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/TheAppealPoint.vue
> +      <p>性格アピールポイント : {{ appealPoint }}</p>
genderみたいにnumberから文字を取得する部分以外は同じコンポーネントで大丈夫じゃないかな？
`props` に `label, value` を設定する感じ！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/TheUserProfile.vue
> +</template>
ここいい感じだね！
コンポーネントをうまく使えていると思う👍

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/nuxt.config.js
>    axios: {
`$axios` 使えない理由わかった！

これ漏れてる
```js
export default {
  modules: ['@nuxtjs/axios']
}
```
https://axios.nuxtjs.org/setup

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/plugins/components.js
> +import UserProfileComponent from "~/components/post/TheUserProfile.vue";
コンポーネントに `Component` ってつけるの冗長なのでやめよう！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/mypage/entrie/entry-admin.vue
> +<style scoped></style>
今更気がついたけど、ファイルパスの `entrie` って単語存在しないね。 `entries` か `entry` かな？
ファイル名も冗長なので `mypage/entry/admin.vue` で良いかと。
他のファイルも同様

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/frontend/plugins/components.js
> +Vue.component('UserProfileComponent', UserProfileComponent);
コンポーネントもこれだとグローバルスコープになるので禁止でお願いします。
使う場所でimportするようにしてください！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/models/db/post_image_db.go
> +func (db *Database) FindPostImagePathList(postId string) []entity.PostImage {
とってくるの `ImagePath` だけじゃないし、 `FindPostImages` じゃダメかな？

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/models/db/post_image_db.go
> +		Joins("left join post_images"+
ここ、欲しいのはpost_idに紐づく `PostImage` 全件だよね？
それなら
```go
err := db.connection.Table("post_images").Where("post_id = ?", postId)
```
で良いかと！
joinしなくても取れるので。

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/models/db/post_prefecture_db.go
> +		Where("post_prefectures.post_id = ?", postId).
joinしていないから `post_prefectures .post_id` は `post_id` だけでOKだよね？

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/models/db/user_db.go
> +		Joins("inner join public.users B on A.user_id = B.id").
`users` のスキーマ `public` なの変じゃない？
他のテーブルは `public` じゃないよね？

あとここは `users` テーブルに対するクエリを記載すべき場所なので引数は `postId` じゃなくて `UserId` にしよう！
そしたらクエリもjoinせず、シンプルに `users` をidでとってくるだけの処理になる。

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/models/entity/post.go
> +	PostPrefectureId int    `gorm:"type:int;					"`              //譲渡可能都道府県ID
ごめん、今更気がついたけどここ別テーブルに分ける必要無いね。
`PrefectureId` にしちゃおう！

2021-04-19 01:24 UTC, MasanoriIwakura commented on fosterParentDog/serializers/post_image_serializer.go
> +//複数
命名しっかりしているし、定義見れば分かるからこのコメントやめよう！
他の箇所も同様。

2021-04-19 04:58 UTC, tako-eng commented on fosterParentDog/frontend/nuxt.config.js
>    axios: {
差分に出てないね。。
プロジェクト立ち上げ時にデフォルトで入れているので、また違う問題かな？と思っています。

https://github.com/tako-eng-org/dog_foster_parent_app/blob/d5072833deb31afcf3f09af96fab0958f1d7d06c/fosterParentDog/frontend/nuxt.config.js#L62
```
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',

    'bootstrap-vue/nuxt',
  ],
```
（nuxt.config.js内のブロックの前後は変えていない＆順序は関係ないと認識しているよ）

2021-04-19 04:58 UTC, tako-eng commented on fosterParentDog/frontend/components/post/Image.vue
> +    imagepath: String, //画像URL
本当だ、ここだけ全部小文字だ。
修正しました。ありがとう！

2021-04-19 05:20 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +	r.User = postUserSerializer.Response()
確かに！使い回すことないなら、struct定義の後に{}で書けばいいね。
ありがとう、簡潔に書くことができました。

2021-04-19 05:31 UTC, tako-eng commented on fosterParentDog/frontend/nuxt.config.js
>    axios: {
slackで教えてくれてありがとう！
修正しました。

備忘/
パス間違えて被ってて、それで404エラーになっていただけだった。
```
  axios: {
    prefix: '/fosterparent/api', <-apiいらない。正しくは'/fosterparent/'
  },
```
![image](https://user-images.githubusercontent.com/45517531/115186010-e601d200-a11b-11eb-8ff4-cb40e16b9b44.png)

2021-04-19 05:38 UTC, tako-eng commented on fosterParentDog/controllers/controller/common_controller.go
> +//*******************************************************************
命名ちょっとマシになったみたいでよかった。。ありがとう！
コード見ればわかるよねってコメントは削除しました。
その時は必要と思ったけど後々不要と感じることが多いから、コメントは控えめにするよう気をつける。

2021-04-19 05:40 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +	// post
そうだね、私も今見たら不要と感じたので削除しました！
リーダブルコードを読み返した甲斐あった、命名,コメント系は気をつけます。

2021-04-19 10:51 UTC, tako-eng commented on fosterParentDog/models/db/user_db.go
> +		Joins("inner join public.users B on A.user_id = B.id").
●publicの件
修正しました！
スキーマは全テーブルpublicで、
userだけはpublic.て付けないとエラーになってたの。でも今public取ったらなぜか動いたからpublicなしに直した。

●userIdの件
これは下記理由によって、現行のまま行きたいんだけど、考え方でダメなところあったら教えて。
「投稿IDからUser情報を取得する関数」自体は存在させたいな。

前提：
postテーブルの対象レコード1件内にあるuserIdカラム(user_id)を元に、userテーブルの情報を取得したい。

（A案）下記2段階にする（ちょっと煩雑な気がする）
1. postテーブルの対象1レコードから、userIdを取得する関数を叩く
2. 取得したuserIdをパラメータに、userテーブルからユーザー情報を取得する関数を叩く（他機能でも絶対必要になるやつ）

（B案）（userの方が重みがあると思うのでナシ）
投稿IDをパラメータにする関数である以上post_db.goがふさわしいので、関数を移動する。

↓投稿idに紐づいたuser_idから取得したい情報
```
    "user": {
        "id": 1,
        "created_at": "0001-01-01 00:00",
        "updated_at": "0001-01-01 00:00",
        "name": "tanaka_taro",
        "e-mail": "hoge@gmail.com",
        "twitter_account": "tanaka",
        "nickname": "田中太郎",
        "profile": "はじめまして！田中の自己紹介です。",
        "web_url": "www.google.com"
    }
```

2021-04-19 10:52 UTC, tako-eng commented on fosterParentDog/serializers/post_image_serializer.go
> +//複数
修正しました！
書いた時は必要と思ったけど、確かに不要だ。
指摘ありがとう！

2021-04-19 11:03 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +	publishParam := c.DefaultQuery("publishing", "0") // デフォルト ?publishing=0(公開)
修正しました。
マジックナンバーだめなのは認識あって、ここだけだしいいかなって思って入れちゃってた。
けど、今後バリデーションチェックでも使うし、他の指摘でもらったみたいに設定を変えたくなった時(数値の意味を逆にするとか)に大変だから、数が少なくてもマジックナンバーはだめだと思い知った。
マジックナンバーだめぜったい
```
//公開設定
const (
	private = "0"
	public  = "1"
)
```

2021-04-19 11:07 UTC, tako-eng commented on fosterParentDog/models/db/post_image_db.go
> +		Joins("left join post_images"+
本当だ！これはpost_imagesテーブルにpost_idが入っているから、わざわざjoinしなくて良いね。
言ってもらえるまで気づかなかった...ありがとう！修正しました。

```go
err := db.connection.Where("post_id = ?", postId).Find(&model).Error
```

```
    "post_images": [
        {
            "post_id": 2,
            "post_image_id": 4,
            "image_path": "https://bbsapp-img.s3.us-east-2.amazonaws.com/images/000004.png"
        },
        {
            "post_id": 2,
            "post_image_id": 3,
            "image_path": "https://bbsapp-img.s3.us-east-2.amazonaws.com/images/000002.png"
        }
    ],
```

2021-04-19 11:10 UTC, tako-eng commented on fosterParentDog/models/db/post_prefecture_db.go
> +		Where("post_prefectures.post_id = ?", postId).
こちらも本当だ...なぜややこしく考えてしまったのか。
post_prefecturesテーブル単体で完結するね。指摘ありがとう、修正しました。

```go
var model []entity.PostPrefecture
err := db.connection.Where("post_id = ?", postId).Find(&model).Error
```

```
    "post_prefectures": [
        {
            "post_id": 2,
            "post_prefecture_id": 2
        },
        {
            "post_id": 2,
            "post_prefecture_id": 10
        },
        {
            "post_id": 2,
            "post_prefecture_id": 11
        }
    ],
```

2021-04-19 11:22 UTC, tako-eng commented on fosterParentDog/models/entity/post.go
> +	PostPrefectureId int    `gorm:"type:int;					"`              //譲渡可能都道府県ID
ごめん、私が間違えてヘンなことしてるかもしれないから、確認させてほしい！
（別テーブルに〜、のくだりがちょっと理解しきれていないかも）

前提として、
この`postテーブル`の`PostPrefectureId`カラムは現在使っていない。
当初用意した理由は、正規化した時に`PostPrefectureテーブル`のidと連携させるカラムとして作った。
しかし、`PostPrefectureテーブル`には`post_idカラム`が存在していて、
現行ではAPIを叩く時も`PostPrefectureテーブル`だけで完結しているので、
この`postテーブル`では使用する機会がない。

上記をふまえて、どのアクションが望ましいかな？
A：`Postテーブル`の`PostPrefectureIdカラム`は、使う場所がないので削除しよう。
B：カラムは削除しなくて良いけど、カラム名を`PrefectureId`に変更しよう。
C：何もしなくてよい。（現行）
D：その他

私はAかCかな、と思っている。

2021-04-19 11:30 UTC, tako-eng commented on fosterParentDog/models/db/post_image_db.go
> +func (db *Database) FindPostImagePathList(postId string) []entity.PostImage {
確かに。post_idとか他の要素も取るね。
`FindPostImages`に修正しました！（`FindPostPrefectures`も合わせて修正済）

2021-04-19 11:57 UTC, tako-eng commented on fosterParentDog/models/db/post_db.go
> +func (db *Database) FindIndex(page string) []entity.Post {
ほんとだ。postman叩いて試したつもりが、完全に見落としてた、指摘ありがとう。
修正したものの、公開パラメータがうまく効いてくれなくて、調査中です。
（map化は後機能でクエリ増えた時にやるかも）

2021-04-19 12:09 UTC, tako-eng commented on fosterParentDog/frontend/components/post/TheAppealPoint.vue
> +      <p>性格アピールポイント : {{ appealPoint }}</p>
なるほど！
そうだね、propsにラベル情報を渡せば、共通化できるね。

相談とかでなくメモレベルであれだけど。。
どこからどこまでを共通のコンポーネント化するか、すっごい悩んでて、今のところ下記くらいまでは分割してみようかと思って、修正しているよ。
・文字列を表示する/文字列を入力する(単数)
・ラベルを表示する/ドロップダウンで選択する(単数)
・画像系(単数)
・画像系(複数)
・読み込み専用系
・ユーザー情報を表示する系

なんとなく「こうしたらいいんじゃないかな？」みたいなのはあるんだけど、分割する粒度が定まらないのよね（今後画面や項目が増えた時、どう影響するのかみたいなのが、まだ想像できていない）。ここは、実際に入力画面をやってみてからもっと細かくしたりまとめたり、試行錯誤するかも。

2021-04-20 11:06 UTC, tako-eng commented on fosterParentDog/models/db/post_db.go
> +func (db *Database) FindIndex(page string) []entity.Post {
公開/非公開パラメータを渡すよう、修正しました。

2021-04-20 11:08 UTC, tako-eng commented on fosterParentDog/frontend/components/post/TheAppealPoint.vue
> +<template>
削除しました。
Vueの命名規則、みたいな記事を読んで参考にしてつけた、「1度しか使わないことが決まってるコンポーネントは頭にTheをつけよう」みたいなお話だった。
けど、実務でvue使ってる人に色々聞いたら、あんまりやらないらしく。
自分でも（ややこしいな...）と思いながらやってたから、削除してよかった。
指摘ありがとう！

ちなみにコンポーネントをまとめたので（別指摘）、このファイルは削除しました。

2021-04-20 11:15 UTC, tako-eng commented on fosterParentDog/frontend/components/post/TheGender.vue
> +      <p>性別 : {{ $getLabel($GENDER, gender) }}</p>
グローバル定義しているところを全修正して、importしないと使えないようにしました。
pluginsに定義してnuxt.config.jsでグローバル設定する、という方法をやめて、
今はcomponentに全部持たせている状態。

以下、今後直す可能性あり、の備忘もかねて。（vueやってる人に相談して考えたこと）
今はただの文字列や定数だからいいけど、今後の機能でcomponentよりもstore（vuexのstateに持たせる）に定義したほうが良い情報も出てくる（ECでいうカート内容みたいな。私のpjでいうとユーザー情報とか？）はず。
なので、今後機能を作る時にまとめてstoreに移動させる可能性あり。
今は規模が小さいのと、表示でしか使ってないからcomponentに置いてます。

2021-04-20 11:17 UTC, tako-eng commented on fosterParentDog/frontend/plugins/components.js
> +Vue.component('UserProfileComponent', UserProfileComponent);
修正しました。
今後、グローバルスコープはなしのつもりで進める！

2021-04-21 23:30 UTC, MasanoriIwakura commented on fosterParentDog/models/db/user_db.go
> +		Joins("inner join public.users B on A.user_id = B.id").
これは2段階で取得するようにしましょう！
1. post_idからpostsを検索
2. 1で取得したpostsに設定されたuser_idを使用してusersを検索

2021-04-21 23:33 UTC, MasanoriIwakura commented on fosterParentDog/models/entity/post.go
> +	PostPrefectureId int    `gorm:"type:int;					"`              //譲渡可能都道府県ID
> このpostテーブルのPostPrefectureIdカラムは現在使っていない。

まず、使わないものは消そう。

postとPostPrefectureは1対1だよね？
複数登録できるっけ？

1対1だったらpostにPostPrefectureId残してそこにデータを登録して欲しい。joinする意味無いので。
1対多だったらこのままでOKだけど、PostPrefectureIdは消してください！

2021-04-22 00:13 UTC, MasanoriIwakura requested changes
レビューしました！
一部しか指摘していないので、同様の箇所は横展開お願いします。

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/const/const.vue
> +      GENDER_TITLE: "性別",
この辺のラベルは変数持ちしないで、使用箇所で直接引数に指定して大丈夫！
使い回すことそんなに無いと思うし。
かえってメンテコスト上がるし

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/const/const.vue
> +        }
ここは1つのソースにしないで分けてください。
`genders.js` や `prefectures.js` で値管理するイメージ。 `component` じゃ無いのでJSファイルにしてください。

別途 `components/GenderList.vue` や `components/PrefectureList.js` を作成してそこから呼ぶようにしよう！

イメージ
```js
<template>
  <div class="genders">
    <select v-model="selected">
      <option v-for="gender in genderList" v-bind:value="gender.value">
        {{ gender.label }}
      </option>
    </select>
  </div>
</template>

<script>
import genders from "../const/genders`;

export default {
  data() {
    return {
      genderList: genders,
      selected: "",
    }
  }
}
</script>
```

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/ImageList.vue
> +import ImageOne from "~/components/post/Image";
ここ別名にせずに素直に `Image` で良いかと！

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/ImageList.vue
> +      isView: true,
これどこかで使ってる？

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +      isView: true,
`isView` に違和感が。viewは「見る」って意味だから何用か分かりにくい。

表示・非表示だったら `visible` とか
編集禁止だったら `readonly` ならシンプルかと。

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +<template>
コンポーネント名(ファイル名)だけど、 `Dropdown.vue` で大丈夫！
パラメータで `readonly` の時はラベルになる。的なイメージ。

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +    CON,
`CON` どこでも使っていないよね？
あと、命名規則的に `con` が良いかな。
`const` はJSだと予約語なので、 ファイルから `consts.js` にして `consts` にするのもあり

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +import ImageTop from "~/components/post/Image";
あんまり別名使いすぎるとぱっと見分かりにくくなるから名称がバッティングする時以外は控えよう！

2021-04-22 00:13 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/index.vue
> +          }).catch(err => alert(err));
デバッグ中は良いけど、エラーアラートはユーザーに見せるものでは無いので
`console.error` に修正してください。

2021-04-22 11:56 UTC, tako-eng commented on fosterParentDog/frontend/components/const/const.vue
> +      GENDER_TITLE: "性別",
修正しました！
「トップ画面、詳細画面、編集画面、の3つでは最低使うしな〜」と思ってなんとなく変数にしたんだけど、やりすぎもよくないんだね。thx

2021-04-22 12:03 UTC, tako-eng commented on fosterParentDog/frontend/components/post/ImageList.vue
> +import ImageOne from "~/components/post/Image";
これはそのまま行きたいかな？
<Image>っていう古いタグがあるらしく、
https://developer.mozilla.org/ja/docs/Web/HTML/Element/image

使おうとするとエディタに心配されるから（予約語優先か）ネーミング少しズラしたほうがいいかな、って思って！
![image](https://user-images.githubusercontent.com/45517531/115710556-7276f380-a3ad-11eb-9686-0458216ba76a.png)

2021-04-22 12:07 UTC, tako-eng commented on fosterParentDog/frontend/components/post/ImageList.vue
> +      isView: true,
isView(見るときかどうかのprops)、使ってない。
そもそも今のところ表示専用のコンポーネントだから、削除します。

2021-04-22 12:28 UTC, tako-eng commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +      isView: true,
（未解決）
そっか。「表示用（`getLabel()`でラベル取得してテキスト表示） or 編集用（ドロップダウンで入力）のどちらにするかを指定する用のprops」なんだけど、どうしよかな、
そもそも表示用と入力用とでコンポーネント分けたほうがいいかもしれないと今思った。
表示したいことと入力したいことが1ページ内に混在することって多分今後もないから、そもそもコンポーネント自体分けたほうがいいような、全ての項目でprops1個増えるほうが大変な気もしてる。

（A）そもそも表示と入力でコンポーネントを分ける（これによって困ることはないか考える）
（B）props名を`input`に修正する。`input=true`の時は入力モードとしてドロップダウン等入力フォームを表示する、`input=false`の時は表示モードで、テキスト(性別`女の子`等を表示する)
（C）B案でprops名が違うやつ
（D）その他

AとBやってみて、読みやすい方を採用しようかと思っています。

2021-04-22 12:32 UTC, tako-eng commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +      isView: true,
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r617972903
readonlyで読み込み

2021-04-22 12:36 UTC, tako-eng commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +<template>
ありがとう！
`Dropdown.vue`に修正しました。（同じノリで`TextOrTextBox.vue`は`TextBox.vue`、みたいに水平展開済）

表示と入力のコンポーネントは1つにまとめた方がやっぱりいいのか。
じゃあreadonly=trueで表示用、falseで編集用、みたいにしてみる。
分けた方がいいきもするし、一緒でもいい気がするし、悩んでたけど決めてもらえたからやってみるね。thx

2021-04-22 13:01 UTC, tako-eng commented on fosterParentDog/models/entity/post.go
> +	PostPrefectureId int    `gorm:"type:int;					"`              //譲渡可能都道府県ID
なるほど！
postとPostPrefectureは1:nの関係だよ、
post.idひとつ（つまり1投稿）に対して、譲渡可能都道府県が埼玉・千葉・東京...みたいに複数指定可能な感じ。
というわけで、PostPrefectureIdカラムを削除します。指摘ありがとう

2021-04-23 13:14 UTC, tako-eng commented on fosterParentDog/frontend/components/post/ImageList.vue
> +import ImageOne from "~/components/post/Image";
ややこしくなるから、コンポーネントのファイル名を変更しました。これでファイル名とインポート先の変数名が一致するし、HTML標準タグとも衝突しないので安心。
Image.vue -> ImageOne.vue

2021-04-23 13:14 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +import ImageTop from "~/components/post/Image";
`Image.vue`というコンポーネントを、`ImageOne.vue`にリネームしました（他コメントでも出た話）。
`Image`というHTML標準タグがあって、コンポーネントタグとバッティングしてしまうのを回避するため。

それに伴い、ここは
```
import ImageOne from "~/components/post/ImageOne";
```
コンポーネント名と変数名が一致するので、ちょっとわかりやすくなったかと！

2021-04-23 13:49 UTC, tako-eng commented on fosterParentDog/frontend/components/const/const.vue
> +        }
サンプルまでありがとう！わかりやすくて助かった
指摘の通り、修正しました。

- 表示モードではラベルを取得するもの
　-> リストをコンポーネント(.js)に分ける & 表示/入力は項目(gender,spay等)ごとにコンポーネント(.vue)に分ける
- 表示モードでは文字列を取得するもの
　-> コンポーネント(.vue)1つにまとめる`TextBox.vue`

2021-04-23 13:51 UTC, tako-eng commented on fosterParentDog/frontend/components/post/ImageList.vue
> +import ImageOne from "~/components/post/Image";
下記修正しました。（`Image.vue`を`ImageOne.vue`に修正し、HTML標準タグ`Image`とのバッティングを回避）
https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r619210275

2021-04-23 13:55 UTC, tako-eng commented on fosterParentDog/frontend/components/post/LabelOrDropdown.vue
> +    CON,
確かにここでは使ってないや...試行錯誤のゴミが残ってました、削除済。

https://github.com/tako-eng-org/dog_foster_parent_app/pull/24#discussion_r619235206
また、上記の修正で、ラベル取得が必要な項目については個別のコンポーネントを作成したので、このDropdown.vueは不要になった。削除します。

予約語について、今後使うときがきたら気をつける！ありがとう

2021-04-23 14:13 UTC, tako-eng commented on fosterParentDog/frontend/pages/index.vue
> +          }).catch(err => alert(err));
確かに。alertにしたら丸見えだね、`console.error(err)`に修正しました。

2021-04-23 14:18 UTC, tako-eng commented on fosterParentDog/frontend/pages/mypage/entrie/entry-admin.vue
> +<style scoped></style>
存在しない単語、確かに。
これ、ディレクトリ構成考える時に作ったテストファイルの消し忘れで近々で不要なので、ディレクトリもファイルも削除しました。いらんもん見せてごめん

2021-04-24 10:46 UTC, tako-eng commented
今日はmtg&丁寧なレビューありがとう！
おかげさまで、フロントのコンポーネント周りがだいぶスッキリしました。

●前回からの主な修正
- constリスト（genderList等）を綺麗にした。各ファイルのディレクトリ構造を変更したり、項目リストをオブジェクトにした。各項目のコンポーネントでは`{{ genderValue(itemValue) }}`で値取得できるイメージ（各論になるけど、value値からラベルを取得する関数getLabel()は不要になったので削除した）。
- バックエンドで、ユーザー情報を取得する時の挙動が綺麗になった（postsとusersの切り分けを明確にした）。
- vueのホットリロードが可能に（教えてもらったやつ。ありがとう！）。
- その他、命名を修正etc

●今回やらなかったこと、次画面機能以降に見送ること
- 各項目の表示/入力をv-if v-elseで分けており、これをまとめること。まだ入力画面を作成していないので、次画面機能（投稿編集画面）実装時に試行錯誤する予定です。TODOコメント差込済みなので忘れない。

2021-04-26 01:42 UTC, MasanoriIwakura approved these changes
お疲れ様でした！！
すごく良くなったと思う！

TODOはまた今度対応お願いします〜
![LGTM](https://image.lgtmoon.dev/89712)

2021-04-26 01:45 UTC, tako-eng commented
うれしい！たった今、TODOもうまくいきそう（次画面機能で更新するね）。
何度も丁寧なレビューと指摘してくれてありがとう！
マージします。

2021-04-26 01:46 UTC, merged