Feature 16（投稿編集画面機能）
tako-eng-org/dog_foster_parent_app pull request #26
Opened 2021-05-11 16:36 UTC by tako-eng

## チケットへのリンク
#16

## やったこと
- 投稿編集画面の新規作成
- 投稿機能の一部実装

## やらないこと
- 画像アップロード機能の実装
- Update機能の実装（今回はCreateのみ）
- 見栄えを良くすること（最後にまとめてやる予定）

## できるようになること（ユーザ目線）
- 投稿画面にアクセスし、投稿機能の一部（画像アップロード以外）を使用できるようになる。

## できなくなること（ユーザ目線）
- なし

## 動作確認
- ローカルのみ動作確認し、dockerにて画面アクセス及び投稿機能（登録）が使用できることを確認した。

## その他
- 前述の通り、Update機能や画像投稿機能は後日改めて実装予定です。

![image](https://user-images.githubusercontent.com/45517531/117961575-3950f400-b359-11eb-9c02-be03f721c0a1.png)
(中略)
![image](https://user-images.githubusercontent.com/45517531/117961594-4372f280-b359-11eb-8f24-dda1f37b60a3.png)

2021-05-12 02:11 UTC, tako-eng commented
プルリク出したので、レビューお願いします！
「今回は一部保留にする機能もあるからレビューもサッと」という運びだけど、一応申し送り事項を書くね。↓

1.
動作確認済みです。
コンパイルエラーや既存画面機能への影響はなし（画像表示機能除く）。

2.
画像系の処理は、後で自分が混乱しないために、
コメントアウトしなくても動作するところはコメントアウトせずそのままにしました。
代わりに＆備忘のため、各所にTODOやFIXMEのコメント（//TODO: 画像処理のため後日改修予定 みたいな）つけた。
1.の通り、動作には影響ありません。

3.
前回に引き続き、ライン数が多くなってしまった。
今回対象の機能以外の話で、なぜこんなにライン数が増えたかというと、
・各コンポーネントの改修で、同じような処理(read/write分岐とか)をたくさん追加した
・シリアライザをエンドポイントごとに分割したことにより、既存ファイル削除/新規追加が発生した
から、やってる内容自体は、前回より少し減ったかな。
今回アーキテクチャが固まったので、ログイン実装以降はもっと減っていく（はず…！）

4.
命名や共通化など、前回#18で指摘を受けたところは読み返して意識して取り組んでみたけど、どうかな。

5.
git雑に使ったせいでマージ要になってしまいごめんなさい。

以上、ボリューム多くて見るのしんどいくてごめんだけど、
レビューよろしくお願いしますm(._.)m

2021-05-12 09:10 UTC, MasanoriIwakura requested changes
流し見だけど数点コメントしたのでよろしく！

2021-05-12 09:10 UTC, MasanoriIwakura commented on fosterParentDog/controllers/controller/post_controller.go
> +	// Post構造体で取得したデータをシリアライザを通しresponseのフィールドに整形して、リスト化する
コードをそのまま日本語にするようなコメントはやめよう！
他の箇所は指摘しないので探して消してください。

2021-05-12 09:10 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/Gender.vue
> +      <form class="form-inline">
formはcomponent使う場所で定義してください〜

2021-05-12 09:10 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/Gender.vue
> +      ioMode: { // read/write時の表示切り替え
これ使ってる？？

あとここの下の部分の意味が分からなかった。この辺りは前に三項演算子の話したところだと思うんだけど、
この書き方だと `ioMode` というオブジェクトに `form-control-plaintext` と `readonly` というキーの値が入っている宣言になっているね。

だから
```js
console.log(ioMode["form-control-plaintext"]);
-> true
```
みたいな状態になっているかと。
何用？？

2021-05-12 09:10 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/ImageList.vue
> +      <ImageOne :objectUrl="objectUrl.object_key"/>
今回は一旦スルーするけど、APIからS3のURLを返却すれば良いから `object_key` ではなくURLにすべき。

2021-05-12 09:10 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/Gender.vue
> +      type: {{ typeof (inputValue) }}
ここ2行は何用？

2021-05-12 09:40 UTC, tako-eng commented on fosterParentDog/controllers/controller/post_controller.go
> +	// Post構造体で取得したデータをシリアライザを通しresponseのフィールドに整形して、リスト化する
今回、自分が理解するまで時間がかかりそうなところはコメント残して全消ししたんだけど、ここって確かに読めばわかるね。
水平展開して、現状残しておきたいところ以外は削除しました。

2021-05-12 09:45 UTC, tako-eng commented on fosterParentDog/frontend/components/post/Gender.vue
> +      type: {{ typeof (inputValue) }}
失礼、これはデバッグ用の消し忘れ。
目が慣れすぎてスルーしてしまってた。
デバッグ用の文言を削除しました。

削除前
![image](https://user-images.githubusercontent.com/45517531/117954038-98ab0600-b351-11eb-84cf-92bdddc1cced.png)

削除後
![image](https://user-images.githubusercontent.com/45517531/117954585-2129a680-b352-11eb-8bde-3540281e63c6.png)

2021-05-12 09:46 UTC, tako-eng commented on fosterParentDog/frontend/components/post/ImageList.vue
> +      <ImageOne :objectUrl="objectUrl.object_key"/>
これは認識あり/後日改修します。コメントありがとう。

2021-05-12 09:55 UTC, tako-eng commented on fosterParentDog/frontend/components/post/Gender.vue
> +      <form class="form-inline">
formは「送信入力する対話型コントロール文書の区間」だから、v-ifがfalseの時だけ適用かなと思ったんだけど（trueは表示のみのためフォームじゃない）、formは親コンポーネントで指定すべき、ということか。

修正前の親コンポーネント
<Spay v-model="post.spay" :readonly="false"/>

修正後の親コンポーネント
<form class="form-inline">
   <Spay v-model="post.spay" :readonly="false"/>
</form>

こんな感じ？修正します。

2021-05-12 10:10 UTC, tako-eng commented on fosterParentDog/frontend/components/post/Gender.vue
> +      ioMode: { // read/write時の表示切り替え
ごめん、これも試行錯誤の時のゴミが残ってた。
丁寧にconsole.logの例示までありがとう、わかりやすかった。

→props:readonly=true/falseで表示/入力分けたくて試行錯誤★
→結局、TextBox.vue以外の"プルダウン表示のコンポーネント"は、上記の変更が難しいと判断
→v-if/v-elseで分岐させる処理にした
→ioModeは★で試行錯誤してた時のdataなので、不要
→削除忘れ（どちらにせよ期待動作しないdataと思う）

削除します。

2021-05-12 10:29 UTC, tako-eng commented on fosterParentDog/frontend/components/post/Gender.vue
> +      ioMode: { // read/write時の表示切り替え
備忘：
data() {}のみだとエラー出力するため、
```
data functions should return an object:
TypeError: Cannot use 'in' operator to search for 'inputValue' in undefined
```
下記に修正した。
```
  data() {
    return {
    }
  },
```

2021-05-12 10:41 UTC, tako-eng commented
@MasanoriIwakura 
レビュー指摘改めてありがとう！
今、指摘箇所を修正終わりました。
（＆画面画像をプルリクのトップコメントに追加しました。）

マージしてOKになったら、声かけてもらえるとうれしい。

2021-05-12 10:51 UTC, MasanoriIwakura requested changes
コメントしました！

2021-05-12 10:51 UTC, MasanoriIwakura commented on fosterParentDog/frontend/components/post/Gender.vue
> +    </div>
あれ、結局Bootstrapのスタイル使ってreadonlyにするのは廃止？
それならそれでOKだけど。

2021-05-12 10:51 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/postEdit.vue
> +      </form>
個別でformタグで囲うんじゃなくて、バックエンドにPOSTしたい情報を全て1つのformで囲ってください。
一回formタグについておさらいした方がいいかもね！

2021-05-12 10:51 UTC, MasanoriIwakura commented on fosterParentDog/frontend/pages/postEdit.vue
> +      let objectKeyByMinPosition = this.post.postImages.filter(e => (e.position === min))[0].object_key;
見落としてた。
何回か説明したつもりだけど、基本は `const` にしよう。
後から値書き換える必要がある場合だけ `let`

for文のindexとかね！

2021-05-12 11:02 UTC, tako-eng commented on fosterParentDog/frontend/components/post/Gender.vue
> +    </div>
yesです。
プルダウンメニュー型の場合のその処理が、可能かもしれないけど私には難しくて、[参考](https://github.com/tako-eng-org/dog_foster_parent_app/pull/26#discussion_r630907932)
渡ってきた値をそのまま表示/入力するテキストボックス型と違って、「readonly=trueのときは受け取ったvalueをそのまま表示、falseのときはfor回してプルダウンメニューを表示」の分岐をまとめることが難しかった。
ということで、今回は見送りにしたい。

ちなみに、テキストボックス型のコンポーネントにはbootstrapのスタイル適用してる。（mtg時に一緒にやって、教えてもらったもの）

2021-05-12 11:32 UTC, tako-eng commented on fosterParentDog/frontend/pages/postEdit.vue
> +      </form>
修正しました！

わかりやすい指摘ありがとう。formについて勉強し直すわ...
公式読んで直した、理解を間違えていた。
<form>を横並び一行にまとめたいときに使うのが、form-inlineなんだね。
[https://getbootstrap.jp/docs/4.1/components/forms/#inline-forms](https://getbootstrap.jp/docs/4.1/components/forms/#inline-forms)

修正後：
親コンポーネントのPOSTしたい情報をsubmitまで<form>で囲んで、
子コンポーネントには"form-group row"、部品には"form-control"を設定して、いい感じに表示するようになったのでこれでいいかな。（横並びにならないけど、こっちの方がみやすくて好きだったので採用。後からまた変えるかも）
![image](https://user-images.githubusercontent.com/45517531/117967976-a451f900-b360-11eb-8207-987c0b4bf943.png)

2021-05-12 11:51 UTC, tako-eng commented on fosterParentDog/frontend/pages/postEdit.vue
> +      let objectKeyByMinPosition = this.post.postImages.filter(e => (e.position === min))[0].object_key;
修正しました。
今は指摘受けたから直したレベルになってしまった。
constの挙動を理解していないから、調べ直します。

今までの理解：
投稿編集画面から画像とpositionを紐づけるため、positionプロパティは可変である。
positionが変わる->動的にminの値も変わる->letでは？と思っていた。

「ここはconstかな！」というところは直したけど、
もし抜け漏れあったら都度指摘もらえると助かります。（何度もごめんね）
なるはやで使い分けできるようになるわ。

2021-05-12 12:02 UTC, tako-eng commented
さっそくの再レビューありがとう！助かるよ。
指摘箇所、修正しました。
- 一部、コメントもらったけど修正なしで進めようとしてる項目あり（1番目）
- 上記以外は修正済

丁寧に見てくれてありがとう、よろしくお願いします。

2021-05-13 03:07 UTC, MasanoriIwakura approved these changes
あとで掘り返して指摘する可能性あるけど、進めること優先で結構流しみになったけど
一旦OK！
マージお願いします。

![LGTM](https://image.lgtmoon.dev/104549)

2021-05-13 05:23 UTC, tako-eng commented
@MasanoriIwakura 
毎回何度も丁寧にレビューしてくれて本当にありがとう。
いわまささんの書いてくれた通り、今回は先に進めることで課題がいくつか残ったので、後々改修するときには改めてよろしくね（後から指摘、大歓迎！）。
次の機能も、引き続きよろしくお願いします！🐹👍
マージします。

2021-05-13 05:25 UTC, merged